[package]
name = "aurora-bot"
version = "0.1.0"
authors = ["Vitaliy Zarubin <keygenqt@yandex.ru"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.28.1"
image = "0.25.5"
ratatui = "0.29.0"
ratatui-image = "4.2.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.136"
